name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v1 
      with:
        # the github_token is built in
        token: ${{secrets.github_token}}
    - uses: kciter/aws-ecr-action@v1
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: sre/helmsync
        region: us-west-1
        tags: ${{ github.sha }},0.1.${{ steps.buildnumber.outputs.build_number}}
        create_repo: false 
